- app/Jobs/ExecSpeedtest.php
- app/Jobs/SearchForSpeedtests.php
- app/Models/Result.php
- database/factories/ResultFactory.php
- database/migrations/2022_08_31_202106_create_results_table.php
- Expanded speedtest results with actual data that can be later reported on
> Expanded speedtest results

- app/Console/Commands/TestInfluxDB.php
- app/Models/Result.php
- app/Observers/ResultObserver.php
- app/Providers/EventServiceProvider.php
- composer.json
- composer.lock
- config.example.yml
- InfluxDB as a support time series database
> Influxdb support

- app/Filament/Resources/ResultResource/Widgets/StatsOverview.php
- app/Models/User.php
- Missing `FilamentUser` trait
- Error when there are no results
> Filament user trait and result stats error

- Dockerfile
- _ide_helper.php
- app/Filament/Resources/ResultResource.php
- app/Filament/Resources/ResultResource/Pages/ListResults.php
- app/Filament/Resources/ResultResource/Widgets/StatsOverview.php
- app/helpers.php
- composer.lock
- resources/views/tables/columns/bits-column.blade.php
- helpers for `formatBytesToBits` and `formatBits`
- show results in descending order
- updated composer dependencies
- this PR fixes an issue first reported in #35 where the panel is reporting `MB/s` instead of `Mbps`
- manually set php ini settings, not needed
_Speedtest Results_
> Report bits not bytes

- app/Filament/Pages/Dashboard.php
- config/filament.php
- resources/views/filament/pages/dashboard.blade.php
- adhoc "Queue Speedtest" button to the dashboard
> Adhoc speedtest button on dashboard page

- .dockerignore
- .gitignore
- .phpstorm.meta.php
- app/Console/Commands/TestInfluxDB.php
- app/Filament/Pages/Dashboard.php
- app/Filament/Pages/General.php
- app/Filament/Pages/Settings/General.php
- app/Filament/Pages/Settings/InfluxDb.php
- app/Jobs/SearchForSpeedtests.php
- app/Observers/ResultObserver.php
- app/Providers/FilamentServiceProvider.php
- app/Settings/GeneralSettings.php
- app/Settings/InfluxDbSettings.php
- composer.json
- composer.lock
- config.example.yml
- config/settings.php
- database/migrations/2022_10_21_104903_create_settings_table.php
- database/settings/2022_10_21_105703_create_general_settings.php
- database/settings/2022_10_21_130121_create_influxdb_settings.php
- docker/deploy/etc/s6-overlay/scripts/startup
- moved site settings to filament
- moved speedtest settings to filament
- moved influxdb settings to filament
- `config.yml` from the build process
- `symfony/yaml` as a compose dependency
_Site and Speedtest Settings_
_InfluxDB Settings_
> Replace config.yml with settings UI

- .github/workflows/publish-image.yml
This PR adds support for building the container as both AMD64 and ARM64. See #32 
Base image supports linux/amd64, linux/arm/v7, and linux/arm64 
Appears to work as expected when running on Raspberry Pi 4 running Alpine Linux 3.16
```
pi-4-1:~# uname -a
Linux pi-4-1 5.15.62-0-rpi4 #1-Alpine SMP PREEMPT Wed Aug 24 17:55:41 UTC 2022 aarch64 GNU/Linux
pi-4-1:~# docker logs -f 5f51b19f1a54
--------------------------------------------------------------------
____                             ____  _     _        _   _
/ ___|  ___ _ ____   _____ _ __  / ___|(_) __| | ___  | | | |_ __
\___ \ / _ \  __\ \ / / _ \  __| \___ \| |/ _` |/ _ \ | | | |  _ \
___) |  __/ |   \ V /  __/ |     ___) | | (_| |  __/ | |_| | |_) |
|____/ \___|_|    \_/ \___|_|    |____/|_|\__,_|\___|  \___/| .__/
|_|
Brought to …
```
> Add basic multi-arch build support

- app/Policies/FailedJobPolicy.php
- app/Providers/FilamentServiceProvider.php
- `500` that was thrown when accessing `env` variables directly in production, should use the `config()` helper instead
> Use config helper for debug policies

- app/Filament/Resources/ResultResource/Pages/ListResults.php
- app/Filament/Widgets/StatsOverview.php
- composer.lock
- automatically refresh `/dashboard` stats and `/results` table
closes #122
> Automatically refresh dashboard

- .github/workflows/ci.yml
- _ide_helper.php
- app/Observers/ResultObserver.php
- app/Policies/FailedJobPolicy.php
- composer.lock
- tests/Feature/ExampleTest.php
- `ci.yml` to ensure a basic working app and code quality
> CI workflow

- app/Filament/Pages/Settings/NotificationPage.php
- when testing mail notifications if there are no recipients throw a warning notification
> make sure there are recipients or throw a warning

- Dockerfile
- `SSL_MODE` to "mixed" so the ports `80` and `443` can be mapped to
> Enable mixed ssl mode so port 80 or 443 can be used

- database/migrations/2022_10_24_152031_create_notifications_table.php
- docker-compose.yml
- use `$table->json('data')` column type for PostgreSQL databases in the notifications table, closes #184
> Fix for pgsql notifications table

- .github/workflows/cd-docker-hub.yml
- .github/workflows/cd-ghcr.yml
- app/Providers/FilamentServiceProvider.php
- docker/8.1/Dockerfile
- having both builds in the same workflow didn't work so trying to split them apart.
> Split image build processes

- app/Filament/Widgets/RecentJitterChart.php
- app/Models/Result.php
- app/Providers/FilamentServiceProvider.php
- use null safe model helper for chart data, closes #217
> null safe model helper for chart data

- app/Filament/Widgets/RecentJitterChart.php
- app/Filament/Widgets/RecentPingChart.php
- app/Filament/Widgets/RecentSpeedChart.php
- chart date range filter and added default filter value, closes #221
> fixed chart query date filter

- app/Filament/Widgets/StatsOverview.php
- check for a result before making the description, closes #234
> check for a result before making the description

- config/filament.php
The favicon was not displayed, because the request was made to `/var/www/html/public/img/speedtest-tracker-icon.png` and not `/img/speedtest-tracker-icon.png`
> Fix favicon

- app/Filament/Pages/Dashboard.php
- app/Filament/Widgets/StatsOverview.php
- app/Models/Result.php
- app/helpers.php
- resources/views/filament/pages/dashboard.blade.php
- % changed for download, upload and ping stats vs. the previous result
- moved the datetime of the last speedtest to below the stats widgets
- only render stats widgets and charts if there are actually results
_Updated header widgets_
> Percent change on stats widgets

- app/Providers/FilamentServiceProvider.php
- app/helpers.php
- `percentChange()` function needs to return a string as the `number_format()` function does [php docs reference](https://www.php.net/manual/en/function.number-format.php), closes #255
> number_format returns a string

- app/Filament/Widgets/RecentSpeedChart.php
- app/helpers.php
Addresses #232
This change unconditionally formats the recent speed chart in megabits instead of using the "formatBits" function that uses floor function to format the nearest whole number.
Before the graph would send a result in gigabits to a lower y-axis value 
Now the graph correctly displays gigabits converted to megabits
This resolves the megabit to kilobit issue as well.
> Always format to megabits in recent speed chart

- app/Filament/Pages/Settings/GeneralPage.php
- app/Rules/ValidCronExpression.php
Using the [CronExpression](https://github.com/dragonmantank/cron-expression) library, this addition ensures that a cron expression is valid in settings before allowing the user to save it.
Addresses #278
The `ValidCronExpression` [Laravel rule](https://laravel.com/docs/9.x/validation#custom-validation-rules) was generated using the following command
```sh
php artisan make:rule ValidCronExpression --invokable
```
Invalid cron expressions are saved without an error.
On Save, invalid cron expressions are not saved and the error is reflected in a UI message.
> Add cron expression form validation

- .env.example
- app/Providers/AppServiceProvider.php
- config/app.php
> force https

- app/Filament/Pages/Settings/NotificationPage.php
- app/Forms/Components/TestTelegramNotification.php
- app/Listeners/SpeedtestCompletedListener.php
- app/Listeners/Threshold/AbsoluteListener.php
- app/Settings/NotificationSettings.php
- app/Telegram/TelegramNotification.php
- composer.json
- composer.lock
- config/services.php
- database/settings/2022_12_22_125055_create_telegram_notification_settings.php
- resources/views/forms/components/test-telegram-notification.blade.php
- resources/views/telegram/speedtest-completed.blade.php
- resources/views/telegram/threshold/absolute.blade.php
First time contributing to this amazing project, hope you like!
Added Telegram notification channel, it looks like mail channel with multiple senders and threshold notification.
Telegram Bot Token must be configured on `.env` file:
`TELEGRAM_BOT_TOKEN=999999:AAFT8KMLBD78HNFFNVGD`
Result screen shoot:
Please let me know any issues!
> Telegram notification channel

- app/Filament/Pages/DeleteData.php
- app/Filament/Resources/UserResource.php
- app/Jobs/DeleteResultsData.php
- resources/views/filament/pages/delete-data.blade.php
- resources/views/filament/pages/modals/delete-results-data-confirmation.blade.php
- delete speedtest results data from the UI, closes #293 
_Delete data page preview_
> delete speedtest results from the UI

- Dockerfile
- _ide_helper.php
- composer.lock
- config/speedtest.php
- docker/8.1/Dockerfile
- docker/8.2/Dockerfile
- `ext-gd` to Dockerfiles as it's a requirement of new dependencies
> Release v0.11.2

- app/Filament/Pages/Dashboard.php
- app/Filament/Pages/Settings/GeneralPage.php
- app/Filament/Pages/Settings/InfluxDbPage.php
- app/Filament/Pages/Settings/NotificationPage.php
- app/Filament/Pages/Settings/ThresholdsPage.php
- app/Filament/Resources/ResultResource/Pages/ListResults.php
- app/Filament/Resources/UserResource/Pages/CreateUser.php
- app/Filament/Resources/UserResource/Pages/EditUser.php
- app/Filament/Resources/UserResource/Pages/ListUsers.php
- app/Settings/GeneralSettings.php
- database/migrations/2022_12_16_164913_transform_speedtest_server_id.php
- database/settings/2023_03_05_233042_add_content_width_to_general_settings.php
- `content_width` to general settings, closes #431 
_General Settings page_
> Content width setting

- app/Filament/Resources/UserResource.php
- missing `email()` validation on the `UserResource`, closes #444
> added email validation to the user's email address

- app/Filament/Pages/Settings/ThresholdsPage.php
- config/speedtest.php
- missing `GeneralSettings()` class import on `ThresholdsPage`.
> [Bugfix] missing general settings class import

- README.md
- 🐇 Speedtest Tracker.postman_collection.json
- initial api documentation 
- Postman collection for testing purposes
> [Documentation] Initial api documentation

- app/Http/Controllers/API/Speedtest/GetLatestController.php
Fixed the bug that the download speed in the API is incorrectly reported as upload speed
See https://github.com/alexjustesen/speedtest-tracker/issues/81#issuecomment-1466055593
> Bugfix: API download speed is reported as upload speed

- app/Listeners/SpeedtestCompletedListener.php
- app/Listeners/Threshold/AbsoluteListener.php
- resources/views/telegram/speedtest-completed.blade.php
- resources/views/telegram/threshold/absolute.blade.php
- added more details to the Telegram message to include the `site_name`, closes #488 
- formatted the messages to be consistent
> [Feature] more details in telegram notifications

- docker/deploy/etc/s6-overlay/scripts/laravel-automations
Appears to fix alexjustesen/speedtest-tracker#498 where it's trying to write to `/config` before `webuser` has been permissioned.
> Move fix permissions section of laravel-automations

- docker/deploy/etc/s6-overlay/scripts/laravel-automations
This resolves the syntax error in the entrypoint.
Before:
```
speedtest-tracker       | 
speedtest-tracker       | 
speedtest-tracker       | 🐇  Configuring Speedtest Tracker...
speedtest-tracker       | 🙄  Config file not found, creating...
speedtest-tracker       | /entrypoint: 11: [: mysql: unexpected operator
speedtest-tracker       | ⏳  Generating app key...
. . .
```
After:
```
speedtest-tracker       | 📦  Linking storage...
speedtest-tracker       | 💰  Building the cache...
speedtest-tracker       | 🚛  Migrating the database...
speedtest-tracker       | 🔑  Fixing permissions...
. . .
```
> fixing bourne shell syntax error

- .dockerignore
- Dockerfile
This PR contains a number of optimizations to reduce the size of the published Docker image.
> Reduce the size of the published Docker image

- app/Filament/Pages/Settings/NotificationPage.php
- resources/views/filament/forms/notifications-helptext.blade.php
Fixing some spelling errors found on the notification page.
- speetest -> spee**d**test
- trigged -> trigg**er**ed
> Fix spelling errors found on notification page

- app/Telegram/TelegramNotification.php
- Telegram notifications were accidently deleted in the Laravel 10 upgrade, 
closes #582 
closes #585
> [Bug] added back deleted telegram notification class

- .github/dependabot.yml
- _ide_helper.php
- composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.10.1` branch.
- Checkout the `shift-ci-v10.10.1` branch
> Laravel 10.10.1 Shift

- app/Filament/Resources/ResultResource/Pages/ListResults.php
- app/Filament/Widgets/RecentJitterChart.php
- app/Filament/Widgets/RecentPingChart.php
- app/Filament/Widgets/RecentSpeedChart.php
- app/Filament/Widgets/StatsOverview.php
- config/speedtest.php
This PR introduces polling configuration settings via environment variables. `DASHBOARD_POLLING` and `RESULTS_POLLING` default to `5s` and can be disabled by passing `false` as the environment variables to the container. This also accepts a string if you want to extend the polling length (example: `60s`).
```
-e DASHBOARD_POLLING=false
-e RESULTS_POLLING=false
```
- polling config
> [Feature] Polling config for dashboard and results

- _ide_helper.php
- composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.13.5` branch.
- Checkout the `shift-ci-v10.13.5` branch
> Laravel 10.13.5 Shift

- _ide_helper.php
- composer.json
- composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.18.0` branch.
- Checkout the `shift-ci-v10.18.0` branch
> Laravel 10.18.0 Shift

- composer.json
- composer.lock
This PR locks `maennchen/zipstream-php` to version `^2.0` so that 32bit platforms are supported.
- lock `maennchen/zipstream-php` to version `^2.0`
> [Bugfix] Lock maennchen/zipstream-php to ^2.0

- app/Http/Controllers/API/Speedtest/GetLatestController.php
This PR fixes the `failed` result logic. Closes #688 
- fixed `failed` result logic
> [Bugfix] Fixed failed indicator on latest result api

- docker/deploy/etc/s6-overlay/scripts/laravel-automations
This PR fixes the symlink for if sqlite is used.
- sqlite symlink
> [Bugfix] added back sqlite symlink

- app/Console/Commands/ResetUserPassword.php
- app/Jobs/DeleteResultsData.php
- app/Jobs/ExecSpeedtest.php
- routes/web.php
This PR introduces a new CLI command to reset a user's password by using `app:reset-user-password` and providing the email address of the user as an argument. Example `app:reset-user-password admin@example.com`. Closes #718 
- `app:reset-user-password` command
- redirect `/login` to `/admin/login`
> [Feature] Reset user password command

- app/Models/Result.php
This PR refactors InfluxDB method to prevent array key or value not found errors. This will also correctly format data that is missing as `null` instead of `0`.
- `successful` attribute
- if data is missing return `null` not `0`
- refactored data payload for InfluxDB
- #549
> [Feature] Refactored format data for InfluxDB

- docker/deploy/etc/s6-overlay/scripts/laravel-automations
This PR introduces generating an `APP_KEY` environment variable on start up along with throwing a warning if one is missing.
- generate an app key on startup if one doesn't exist in `.env` or as an environment variable
> [Feature] Generate app key on startup

- app/Console/Commands/UpdateUserRole.php
- app/Filament/Pages/Dashboard.php
- app/Filament/Pages/DeleteData.php
- app/Filament/Pages/Settings/GeneralPage.php
- app/Filament/Pages/Settings/InfluxDbPage.php
- app/Filament/Pages/Settings/NotificationPage.php
- app/Filament/Pages/Settings/ThresholdsPage.php
- app/Filament/Resources/ResultResource.php
- app/Filament/Resources/UserResource.php
- app/Models/User.php
- app/Policies/ResultPolicy.php
- app/Policies/UserPolicy.php
- composer.json
- composer.lock
- database/migrations/2023_09_11_225054_add_role_to_users_table.php
- routes/test.php
This PR introduces roles for users, restricts authorization based on policies and lays the ground work for some future improvements.
Closes #511 
- When this feature is released the **first** user will be given the `admin` role.
See the [Authorization docs](https://docs.speedtest-tracker.dev/) for a detailed explanation of what each role and and cannot do.
- `admin`
- `guest`
- `user`
- cli command to update a user's role
- `role` to the `User` model
- scope page and resource authorization to the new roles
- reorganized the form and table for `UserResource`
**Updated user resource**
> [Feature] User role

- app/Filament/Pages/Settings/GeneralPage.php
- app/Filament/Pages/Settings/InfluxDbPage.php
- app/Filament/Pages/Settings/NotificationPage.php
- app/Filament/Pages/Settings/ThresholdsPage.php
This PR fixes a [bug](https://github.com/filamentphp/filament/issues/8555) found that required calling `$this->FillForm()` again when using `mount()` to authorize a settings page.
- settings forms not being filled when authorizing the page
> [Bug] Settings page authorization

- app/Console/Commands/UpdateUserRole.php
- app/Filament/Resources/UserResource.php
- app/Models/User.php
This PR removes the `guest` role as a planned Dashboard update will make it redundant and should have never been added as an option.
- `guest` role
> [Bug} Removed guest role

- app/Filament/Pages/Settings/GeneralPage.php
> [Bugfix] Capture null speedtest server default to prevent the error

- app/Filament/Pages/Settings/GeneralPage.php
This PR updates the label in General Settings to "Display time zone" and adds helper text.
- "time zone" to "display time zone" general settings label
> [Chore] Changed label to display time zone

- resources/views/layouts/app.blade.php
- site name to the Dashboard title for consistency
> added site name to the dashboard

- config/cache.php
- docker/deploy/etc/s6-overlay/scripts/laravel-automations
This PR changes the default cache driver to `file` system as it is more performant than the `database` driver and fine for most cases. Also the cache will now be cleared on startup before checking if an app key exists.
- [Caching](https://docs.speedtest-tracker.dev/other/caching) section to the docs
- changed the default cache driver to the `file` system
- clear existing cache on startup to avoid "app key missing" errors, closes #839
> [Bugfix] Clear cache on startup and default cache driver to file

- app/Http/Controllers/HomeController.php
- resources/views/dashboard.blade.php
- routes/web.php
This PR adds back the latest result timestamp on the dashboard.
- latest result timestamp to the public dashboard, closes #840 
- missing `home` route name
> [Feature] Latest result timestamp on dashboard

- app/Filament/Pages/Settings/GeneralPage.php
- app/Http/Controllers/HomeController.php
- app/Settings/GeneralSettings.php
- database/settings/2023_10_07_113220_add_public_dashboard_enabled_to_general_settings.php
Fixes #855 
- Enable/Disable Public Dashboard setting to general settings (default: enabled)
- If public dashboard is disabled -> redirect to login (as it was before public dashboard was introduced)
> Added public dashboard enabled setting to general settings

- .github/workflows/dev.yml
This PR builds a `dev` tagged image based on the `main` branch when a new PR is merged or daily at 4am to catch any dependency build errors.
- build a `dev` image and publish it to GHCR
> [Chore] Build and publish dev image workflow

- app/Http/Middleware/FrameAllowOptions.php
- config/speedtest.php
This PR makes it so it won't modify the header if `ALLOW_EMBEDS` is empty.
- closes #903 
- `SAMEORIGIN` showing up twice
> [Bug] Don't return SAMEORIGIN twice (Hotfix Release v0.13.3)

- app/Filament/Resources/ResultResource.php
This PR makes `id`, `server`, `download`, `upload`, `ping` and `jitter` columns sortable in the Results table.
Closes #924 
- made more Results table sortable
> [Feature] Made more result columns sortable

- app/Console/Kernel.php
- app/Filament/Pages/Settings/GeneralPage.php
- app/Http/Controllers/HomeController.php
⚠️ WIP - this PR isn't ready for primetime just yet.
This PR looks to address the issues around usage of time zones throughout the application. #846 was a useful exercise in an overly complex solution.
- closes #194
- #242
- #631 
- closes #649 
- closes #659
- #696 
- #800  
- closes #805 
- closes #859 
- closes #916 
- set scheduled tasks time zone
- set `$cron->isDue` to use the current local time to evaluate if a cron is due
- the jank and complexity surrounding dealing with time zones
- no longer need to mount `'/etc/localtime:/etc/localtime:ro'` to pass the host machine's time
- no longer need to pass `TZ` as an environment variable
_Sanity checking time zones, datetimes and conversions to local time_
> [Bug] Refactor usage of time zones

- resources/views/get-started.blade.php
This PR changes the anchor's URL so that the intended destination is used when signing in for the first time.
- closes #930 
- first time auth loop
> [Bug] Use admin url so intended destination is used

- resources/views/get-started.blade.php
This PR implements `@auth` blade helper to dynamically set the url for the admin panel on the getting started page.
- closes #951 
- getting started admin/login link
> [Bug] use auth helper to correctly set the url

- app/Jobs/ExecSpeedtest.php
Removed `ShouldBeUnique` trait from `ExecSpeedtest` job as it can cause instability in some cases when a cache lock can't be obtained.
- `ShouldBeUnique` trait from `ExecSpeedtest` job
> [Bug] Removed should be unique trait from exec speedtest job

- app/Services/SystemChecker.php
Part of the version notification system in an upcoming release detailed in #977.
- system checker for local and remote versions
> [Feature] Added system checker for local and remote versions

- app/Filament/Pages/Settings/GeneralPage.php
- app/Filament/Resources/ResultResource.php
- app/Filament/Widgets/RecentJitterChartWidget.php
- app/Filament/Widgets/RecentPingChartWidget.php
- app/Filament/Widgets/RecentSpeedChartWidget.php
- app/Helpers/TimeZoneHelper.php
- app/Http/Controllers/HomeController.php
- app/Settings/GeneralSettings.php
- database/settings/2023_12_12_234839_add_db_has_time_zone_to_general_settings.php
- resources/views/dashboard.blade.php
- resources/views/livewire/debug/timezone.blade.php
This PR introduces a `db_has_timezone` setting that let's the application know the database is already reporting in the local time.
- `TZ` environment variable was not passed to the application's container.
- Database had a `TZ` environment variable of `America/New_York` which matched the setting in the application's UI.
- Local time was set in the `Time zone` setting under the "General Settings" page.
- `Database has time zone` was enabled.
- `db_has_timezone` to general settings
- changed the layout of the general settings page
_Dashboard_
_Results Screenshot_
_General Settings page_
> [Feature] Database has time zone setting

- .github/workflows/lint.yml
- .github/workflows/test.yml
Linting workflow isn't running when a PR is opened from a forked repo.
- bumped `test.yml` workflow to use `php8.2`
- run `lint.yml` on `pull_request` and `workflow_dispatch`
> [Bug] Workflow updates

- config/mail.php
config/mail.php: Added option to skip SSL certificate verification for self signed certificates
Using the current build the option to send mail with a self hosted SMTP server using a self signed SSL certificate is not possible. Adding the option to disable the verification process with the environmental variable `MAIL_VERIFY_SSL` allows to send mail.
Allowed values for  `MAIL_VERIFY_SSL` are `true` or `false`. Default is `true`
- config/mail.php
` 'verify_peer' => env('MAIL_VERIFY_SSL', 'true'),`
> [MAIL] Send mail with smtp without verifying SSL certificate

- Dockerfile
- docker/deploy/etc/nginx/server-opts.d/security.conf
This PR disabled nginx's x-frame-options header in an attempt to prevent multiple headers.
- disabled `add_header` in `security.conf`
> [Bug] Disable nginx x-frame-options header

- Dockerfile
We have a massive release coming up soon for **[serversideup/php](https://serversideup.net/open-source/docker-php/).** We don't want to create any unnecessary downstream issues 🤠
As of today, changing from "8.2-fpm-nginx" to "8.2-fpm-nginx-v2.2.1" should not have any effect.
Once the beta gets merged, that will be a different story. 😅
More about the beta here:
https://github.com/serversideup/docker-php/discussions/254
- Change base image from `serversideup/php:8.2-fpm-nginx` to `serversideup/php:8.2-fpm-nginx-v2.2.1`
> Lock PHP image into "serversideup/php" v2.2.1

- app/Console/Commands/VersionChecker.php
- app/Console/Kernel.php
- app/Filament/VersionProviders/SpeedtestTrackerVersionProvider.php
- app/Providers/AppServiceProvider.php
- app/Services/SystemChecker.php
- config/speedtest.php
This PR implements the system version checker and provides notifications to the admin user(s) when a new version of Speedtest Tracker is available.
_Heavily_ inspired by how [Ploi Roadmap](https://github.com/ploi/roadmap) handles version checking.
- closes #977 
- `artisan about` now reports the local version and if the local version is out of date.
- check for updates weekly and notify the admin user(s) if one is available via database notification
- use `SystemChecker` instead of `config/speedtest.php` to get the current version.
> [Feature] Check for a new version and notify the admin(s)

- app/Console/Commands/SystemMaintenance.php
- app/Console/Kernel.php
This PR introduces `app:system-maintenance` command to keep the application healthy and hopefully prevent issues like #1006.
- closes #1006 
- system maintenance command
> [Feature] System maintenance command to keep things healthy

- app/Services/SystemChecker.php
- config/speedtest.php
Since `git` is not included in the production image and it increases the size of the image by `~90 MB` this reverts checking the local version to the config file instead.
- closes #1011 
- use config to check local version
> [Hotfix] v0.14.2-beta2

- app/Filament/VersionProviders/SpeedtestTrackerVersionProvider.php
- app/Services/SystemChecker.php
- config/speedtest.php
This hotfix PR addresses the latest error found in #1011.
- instantiate the `SystemChecker` class correctly 🤦‍♂️
> Hotfix v0.14.0 beta3

- app/Http/Middleware/VerifyCsrfToken.php
The PR attempts to fix the invalid token error that is present on the public dashboard when embedding it within an iframe.
- `livewire/*` to verify csrf exception list
> [Bug] added livewire paths to exception list

- docker/deploy/etc/s6-overlay/scripts/laravel-automations
This PR removes initial `cache:clear` on startup which can cause issues on new installs when the database isn't ready yet.
- closes #1078 
- closes #1088 
- closes #1090 
- closes #1092 
- `cache:clear` on startup
> [Bug] Removed initial cache clear on startup

- app/Console/Commands/SystemMaintenance.php
This PR wraps `app:system-maintenance` commands in `try` blocks so it soft fails.
- wrapped system maintenance commands in try block
> [Bug] Wrap system maintenance commands in try to soft fail the command

- _ide_helper.php
- composer.json
- composer.lock
Going to use this for some future stuffs...
- required `timokoerber/laravel-one-time-operations` package
> [Chore] Added one time operations package

- app/Notifications/Telegram/TestNotification.php
- app/Telegram/TelegramNotification.php
- config/speedtest.php
- almost forgot to add `->disableNotification()` method for Telegram notifications 🤷‍♂️
> Release v0.15.1

- app/Console/Commands/SystemMaintenance.php
- config/speedtest.php
This PR changes `SystemMaintenance` command to only clear the `cache` and `view` caches. In #1065 it was identified that clearing the config can stop the container from running correctly.
- `SystemMaintenance` command to only clear the cache and view cache
> Release v0.15.2 (Hotfix)

- app/Console/Kernel.php
- app/Filament/Pages/Settings/GeneralPage.php
- app/Models/Result.php
- app/Settings/GeneralSettings.php
- database/settings/2024_02_19_022251_add_prune_results_to_general_settings.php
This PR introduces a new setting to set the number of days until a `Result` model record is pruned from the database. Default is disabled.
- closes #880 
- prune `Result` model records automatically
> [Feature] Automatically prune results

- config/settings.php
- cache settings values to improve performance
> [Chore] Cache settings values

- app/Filament/Resources/ResultResource.php
- app/Jobs/ExecSpeedtest.php
- app/Models/Result.php
This PR correctly formats failed speedtests and adds the error message when viewing the result.
- error message when viewing a result of a failed speedtest
- docs page for [error messages](https://docs.speedtest-tracker.dev/help/error-messages)
- json data format for failed speedtests
> [Bug] Correctly format failed speedtests

- app/Filament/Exports/ResultExporter.php
- app/Filament/Resources/ResultResource.php
- wrong results value because `_bits` attribute wasn't being used.
> [Bug] Wrong results value

- app/Models/Result.php
This PR fixes the typed format for the return of `download_bits` and `upload_bits`.
- closes #1164 
- typed return for `download_bits` and `upload_bits`
> [Bug] Download and upload bits should be a nullable int

- app/Actions/MigrateBadJsonResults.php
This PR adds an additional check to the match statement to capture `1` and `true` for successful speedtests during data migration.
- closes #1177 
- mentioned in #1175 
- data migration match statement.
> [Bug] Capture 1 or true for successful status

- app/Filament/Resources/ResultResource.php
- app/Helpers/Number.php
This PR fixes a calc error on the dashboard and table views. This **does not** address the API where values are being passed to Homepage or Heimdall yet.
- mentioned in #1176
- closes #1169 
- closes #1180 
- use `Number` helper on results table
- when converting bits use the power of 1000 not 1024 (for bytes)
> [Bug] Fixed incorrect file size bits calculation

- app/Filament/Pages/Settings/ThresholdsPage.php
- app/Filament/Resources/ResultResource.php
- app/Filament/Widgets/StatsOverviewWidget.php
- app/Listeners/Threshold/AbsoluteListener.php
Changed "Ms" with "ms" to indicate millisecond(s) because Ms means megasecond(s) (1 Ms = 10<sup>6</sup> seconds) ([source](https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes))
- "Ms" => "ms"
All "Ms" occurrencies with "ms" across multiple files
| Before | After |
| :---: | :---: |
| ![immagine](https://github.com/alexjustesen/speedtest-tracker/assets/30187360/d16df148-e5e6-4665-be1b-976354a4bbea) | ![immagine](https://github.com/alexjustesen/speedtest-tracker/assets/30187360/1792b996-70be-4539-8ce2-cd01af54d318) |
> Milliseconds should be indicated with "ms" and not "Ms"

- app/Filament/Widgets/RecentJitterChartWidget.php
- app/Filament/Widgets/RecentPingChartWidget.php
- app/Filament/Widgets/RecentSpeedChartWidget.php
- charts query not ordering by latest, closes #1188
> [Bug] Fixed charts query not ordering by latest

- app/Helpers/Number.php
- app/Http/Controllers/API/Speedtest/GetLatestController.php
- routes/api.php
- return `download` and `upload` values as mbit magnitude for Homepage and Organizr dashboards. closes #1176
> [Bug] Return latest speedtest download and upload in mbits

- app/helpers.php
- default download and upload value when assessing if a threshold was breached, closes #881
> [Bug] Added default download and upload value when assessing if a threshold was breached

- app/Actions/Notifications/SendDiscordTestNotification.php
- app/Actions/Notifications/SendWebhookTestNotification.php
- app/Filament/Pages/Settings/NotificationPage.php
This PR does a little 🧹 cleaning when posting to the Discord webhook url.
- standardized use of `webhooks` and `url` across Discord and Webhook notifications.
- use `Spatie\WebhookServer\WebhookCall` for sending a webhook instead of Laravel's `Http` client.
> [CHore] Refactored discord webhooks to use WebhookCall

- app/Http/Controllers/API/HealthCheckController.php
- routes/api.php
With the switch to LSIO image `/ping` is no longer available, this PR provides a `/api/healthcheck` route that returns a `200` code response with a json message.
```json
{"message":"Speedtest Tracker is running!"}
```
- `/api/healthcheck` route that can be used to monitor if the application is up, closes #1228
> [Feature] Added heathcheck API route

- app/Filament/Resources/ResultResource.php
- second server ID reference should of been server host
> [Bug] Dixed missing server host reference

- app/Listeners/SpeedtestCompletedListener.php
- app/Listeners/Threshold/AbsoluteListener.php
- config/speedtest.php
- incorrect Discord webhook url reference, closes #1235
> Hotfix v0.17.2

- app/Listeners/SpeedtestCompletedListener.php
- app/Listeners/Threshold/AbsoluteListener.php
Refactored Discord notifications to use WebhookCall
N/A
- Updated `app/Listeners/Threshold/AbsoluteListener.php` to use `WebhookCall` instead of Laravel's `http` to send the payload
- Updated `app/Listeners/SpeedtestCompletedListener.php` to use `WebhookCall` instead of Laravel's `http` to send the payload
N/A
- Removed imports of Laravel's `http` 
No frontend modifications were made
> [Chore] Refactored Discord notifications to use WebhookCall

- app/Listeners/Database/SendSpeedtestCompletedNotification.php
- app/Listeners/Database/SendSpeedtestThresholdNotification.php
- app/Listeners/SpeedtestCompletedListener.php
- app/Listeners/Threshold/AbsoluteListener.php
- app/Providers/EventServiceProvider.php
- refactored database notification to their own listeners
> [Chore] Refactored database notifications to their own listeners

- app/Listeners/Database/SendSpeedtestThresholdNotification.php
- app/Listeners/Discord/SendSpeedtestThresholdNotification.php
- app/Listeners/Mail/SendSpeedtestThresholdNotification.php
- app/Listeners/Telegram/SendSpeedtestThresholdNotification.php
- app/Listeners/Webhook/SendSpeedtestThresholdNotification.php
- additional log messages when a listener stops because of missing data
- don't proceed with notification if absolute threshold disabled
> [Bug] Don't proceed with notifications if absolute threshold disabled

- app/Listeners/Discord/SendSpeedtestThresholdNotification.php
- app/Listeners/Mail/SendSpeedtestThresholdNotification.php
- app/Listeners/Telegram/SendSpeedtestThresholdNotification.php
- app/Listeners/Webhook/SendSpeedtestThresholdNotification.php
- resources/views/emails/speedtest-completed.blade.php
- resources/views/emails/speedtest-threshold.blade.php
- closes #1281 
- closes #1290 
- don't try to send empty threshold notifications
> [Bug] Don't try to send empty threshold notifications

- app/Filament/Resources/ResultResource.php
This PR adds packet loss to the form view and table, worth noting it doesn't seem like all servers return the packet loss metric.
- packet loss metric, closes #1298
> [Feature] Added packet loss to form view and table

- app/Filament/Pages/Settings/GeneralPage.php
- app/Listeners/Webhook/SendSpeedtestCompletedNotification.php
- app/Listeners/Webhook/SendSpeedtestThresholdNotification.php
- app/Settings/GeneralSettings.php
- app/helpers.php
This PR deprecates general settings `site_name` variable as part of the work detailed in #1258.
- use `config('app.name')` in notifications
- deprecated `site_name` from general settings
> [Chore] Deprecate general settings site name

- app/Console/Commands/UpdateGeneralSettings.php
- app/Filament/Pages/Dashboard.php
- app/Filament/Pages/Settings/GeneralPage.php
- app/Http/Controllers/HomeController.php
- app/Settings/GeneralSettings.php
- config/speedtest.php
This PR deprecated general settings enable public dashboard detailed in #1258.
- `public_dashboard` environment variable
- deprecated general settings enable public dashboard
> [Chore] Deprecate general settings public dashboard

- app/Filament/Pages/Dashboard.php
- app/Filament/Pages/Settings/GeneralPage.php
- app/Filament/Pages/Settings/InfluxDbPage.php
- app/Filament/Pages/Settings/NotificationPage.php
- app/Filament/Pages/Settings/ThresholdsPage.php
- app/Filament/Resources/ResultResource.php
- app/Filament/Resources/UserResource.php
- use `canAccess()` method for pages instead of hooking into the `mount()` method. closes #1226 
- page nav order, not needed.
> [Bug] Use can access method for pages

- app/Filament/Resources/ResultResource.php
- app/Jobs/TruncateResults.php
This PR adds the ability to truncate the results table. This differs from deleting records as it resets the table's primary key.
- closes #1344 
- ability to truncate `results` table from the UI
> [Feature] Added ability to truncate the results table

- app/Filament/Pages/Settings/GeneralPage.php
Switching to https://crontab.guru from https://crontab.cronhub.io/  as the former gives warnings for non-standard cron expressions and offers info on next run etc.
- GeneralPage.php
> Use https://crontab.guru instead of https://crontab.cronhub.io/

- app/Http/Controllers/API/Speedtest/GetLatestController.php
This PR adds display timezone to the `/speedtest/latest` API response. Expands on the work started in #1070.
```json
{
"message":"ok",
"data":{
"id":1,
"created_at":"2024-04-10T01:41:12.000000+00:00",
"updated_at":"2024-04-10T01:41:33.000000+00:00"
}
}
```
```json
{
"message":"ok",
"data":{
"id":1,
"created_at":"2024-04-09T21:41:12.000000-04:00",
"updated_at":"2024-04-09T21:41:33.000000-04:00"
}
}
```
- closes #1375 
- added display timezone to latest speedtest API response
> [Bug] Added timezone to latest speedtest API response

- Dockerfile
- app/Filament/Pages/Dashboard.php
- app/Filament/Widgets/DeprecatedImage.php
- resources/views/filament/widgets/deprecated-image.blade.php
This PR adds a deprecated image warning to the admin panel for anyone who hasn't switched over to the LSIO image.
- closes #1379 
- deprecated image warning to admin panel for my image only
> [Chore] Added deprecated image warning to admin panel

- app/Filament/Exports/ResultExporter.php
This PR adds the packet loss to the CSV export to close https://github.com/alexjustesen/speedtest-tracker/issues/1374
- Add the packet loss to the ResultExporter.php
Test against multiple, when no packet loss is returned by it the field stays empty as expected
> Add Packet loss to CSV export 

- app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
This PR makes the Ookla Speedtest job unique and increases it's timeout in case of a slow connection.
- Ookla Speedtest job will now be unique in the queue which will prevent stacking of jobs.
- increased the job timeout from 60s (default) to 120s, closes #1413
> [Feature] Unique Ookla speedtest job and increased timeout

- app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
When a test failed a new record would be created instead of updating the existing result record, this fixes that issue.
- update existing result record when a test fails, closes #1439
> [Bug] Fixed updating the result record when a test fails

- app/Filament/Pages/Dashboard.php
This PR adds the next speedtest run at date to the dashboard header.
- Next speedtest run at date in the header of the dashboard
**With a schedule**
**Without a schedule**
> [Feature] Display next speedtest run at date on dashboard

- app/Filament/Widgets/RecentDownloadChartWidget.php
- app/Filament/Widgets/RecentDownloadLatencyChartWidget.php
- app/Filament/Widgets/RecentJitterChartWidget.php
- app/Filament/Widgets/RecentPingChartWidget.php
- app/Filament/Widgets/RecentUploadChartWidget.php
- app/Filament/Widgets/RecentUploadLatencyChartWidget.php
- config/app.php
This PR adds a new `CHART_DATETIME_FORMAT` environment variable to control the datetime format in charts only.
```
- CHART_DATETIME_FORMAT="M. j - G:i"
```
- chart datetime format environment variable
> [Feature] Added chart datetime format environment variable

- app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
- composer.json
- composer.lock
- config/speedtest.php
- docker/8.3/Dockerfile
This PR uses `ping` to check for internet connections instead of HTTP `get` requests.
closes #1484 
- use ping instead of http get
> [Feature] Use ping instead of a HTTP get request to check for internet connection

- app/Filament/Resources/ResultResource.php
Using the model attribute was causing performance issues, the results table is now referencing the database columns instead.
- result table columns
> [Bug] Use table columns not attributes on results table

- app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
- config/speedtest.php
This PR makes checking for an internet connection optional. If `SPEEDTEST_PING_URL` is false, empty or null it will skip the check.
closes #1501 
- made checking for internet connection before a speedtest optional
> [Feature] Made checking for internet connection optional

- app/Mail/SpeedtestCompletedMail.php
- app/Mail/SpeedtestThresholdMail.php
Notify on every speedtest run failing:
[2024-06-11 12:38:08] production.ERROR: Undefined variable $event {"exception":"[object] (ErrorException(code: 0): Undefined variable $event at /app/www/app/Mail/SpeedtestCompletedMail.php:51) [stacktrace]
A short description of the pull request changes should go here and the sections below should list in detail all changes. You can remove the sections you don't need.
Fix issue with Notify on every speedtest run failing 
- one
- two
- /app/www/app/Mail/SpeedtestCompletedMail.php 
- two
- one
- two
- one
- two
If this PR has any UI/UX changes it's strongly suggested you add screenshots here.
> Fix issue with Notify on every speedtest run failing 

- app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
If a server ID is present it will now be written to the result record if the test fails. This will help track down missing servers mentioned in #1519.
- server ID to failed tests
> [Feature] Write the server id to the result on failed tests

- app/Filament/Exports/ResultExporter.php
- app/Filament/Resources/ResultResource.php
- app/Models/Result.php
Some ISPs have multiple server across the countries / network. When testing with multiple of these server it can useful to see their location as the Name will be the same. 
- Add Server location to results and export
> Add Server location to results and export

- app/Filament/Resources/ResultResource.php
To close https://github.com/alexjustesen/speedtest-tracker/issues/1545
In the results tables and pop up view:
- Round up the Packet loss with 2 and add a `%`
- Round up the Upload and Download latency  with 0 and add `ms`
- Round up the Ping  with 0 and add `ms`
**Before:** 
**After**
> Fix value rounding 

- app/Events/SpeedtestCompleted.php
- app/Events/SpeedtestFailed.php
- app/Events/SpeedtestStarted.php
- app/Http/Controllers/HomeController.php
- app/Http/Middleware/PublicDashboard.php
- app/Jobs/InfluxDBv2/WriteCompletedSpeedtest.php
- app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
- app/Jobs/TruncateResults.php
- app/Mail/SpeedtestCompletedMail.php
- app/Mail/SpeedtestThresholdMail.php
- app/Notifications/Telegram/SpeedtestNotification.php
- bootstrap/app.php
- pint.json
- routes/web.php
Moved public dashboard check to middleware so it can be reused.
- `PublicDashboard` middleware
> [Chore] Added public dashboard middleware

- app/Filament/Pages/Settings/NotificationPage.php
This PR adds a placeholder text for the notification endpoint. To five the user an idea what the giving url/id should look like.
> Add Placeholder text for notifications

- app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
- closes #1613 
- default `serverId` to null when executing a speedtest if it fails
> [Bug] Default server id to null when executing speedtest

- app/Actions/Notifications/SendPushoverTestNotification.php
- app/Filament/Pages/Settings/NotificationPage.php
- app/Listeners/Pushover/SendSpeedtestCompletedNotification.php
- app/Listeners/Pushover/SendSpeedtestThresholdNotification.php
- app/Settings/NotificationSettings.php
- database/settings/2024_02_22_144680_create_pushover_notification_settings.php
- resources/views/pushover/speedtest-completed.blade.php
- resources/views/pushover/speedtest-threshold.blade.php
To cross Pushover of the list https://github.com/alexjustesen/speedtest-tracker/issues/40 
- Add Pushover to the notification page
- Add helperText to the User Key, API Token and url
- Add Pushover to the settings migration
- Add User Key and API Token to the input field
Settings; 
Pushover:
> Add Pushover Notifications via Webhooks

- resources/views/gotify/speedtest-completed.blade.php
- resources/views/gotify/speedtest-threshold.blade.php
- resources/views/ntfy/speedtest-threshold.blade.php
- resources/views/slack/speedtest-completed.blade.php
- resources/views/slack/speedtest-threshold.blade.php
While doing some double check testing I noticed that for some the layout for the bold texts was not correct. This PR fixes them :)
> Fix notifications layouts

- config/speedtest.php
This release is just dependency updates so we can rule it out while trying to identify the issue in #1603.
> Release v0.20.9

- config/settings.php
Don't cache settings by default, this was causing issues when writing new settings to the database.
- closes #1652
> [Bug] Don't cache settings by default

- resources/views/emails/speedtest-completed.blade.php
- resources/views/emails/speedtest-threshold.blade.php
Due to a oversight by me the mail notifications did not work anymore after adding the Ooka URL  in it.
Closes https://github.com/alexjustesen/speedtest-tracker/issues/1656
Tests:
- Fix the mail notifications for Completed tests
- Fix the mail notifications for threshold breaches
(Promise to keep my next contributions to charting improvments, less chance to break things 😉)
> [Bug] Fix the mail notifications not being sent 

- app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
I was trying to set up the ping url but I included the protocol which seems to not work with thie ping package. I added a little validation and removal of the protocol to remove this issue for others...
I'm not sure where the documentation should be updated to add this new error here: https://docs.speedtest-tracker.dev/help/error-messages
- added ping url validation
- removed ping url protocol
> Validate ping url

- README.md
In README, the docker tag is not always updated with the latest version tag (at least for now). So maybe it's better to use `latest` tag instead in the README to ensure that the new user will always get the latest version available.
- Docker tag in `README.md` from `0.20.6` to `latest`
None
> Use latest docker tag in README

- app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
- config/speedtest.php
This PR disables checking for an internet connection before running a speedtest, this regression will be fixed in an upcoming release.
- ref: #1754
> Hotfix v0.21.4

- config/speedtest.php
Nothing fancy, this release patches https://github.com/laravel/framework/security/advisories/GHSA-gv7v-rgg6-548h
> Release v0.21.6 (Security Release)

- app/Actions/Speedtests/RunOoklaSpeedtest.php
- app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
> [Chore] Only skip scheduled tests

- app/Enums/ResultStatus.php
- app/Events/SpeedtestChecking.php
- app/Events/SpeedtestRunning.php
- app/Jobs/CheckForInternetConnectionJob.php
- app/Jobs/Ookla/RunSpeedtestJob.php
This PR adds additional status states to track the progress of the process lifecycle.
- `Checking` result status, for when a test has been picked up by a worker and is evaluating if it can/should run the test.
- `Running` result status, for when the Speedtest CLI is running and is awaiting results.
> [Feature] Added result checking and running statuses

- app/Enums/ResultStatus.php
- app/Events/SpeedtestBenchmarking.php
- app/Jobs/Ookla/BenchmarkSpeedtestJob.php
- app/Jobs/Ookla/CompleteSpeedtestJob.php
- app/Jobs/Ookla/ProcessSpeedtestBatch.php
- app/Jobs/Ookla/RunSpeedtestJob.php
- app/Models/Result.php
- database/migrations/2024_11_22_235011_add_benchmarks_to_results_table.php
This PR adds any active benchmarks (aka thresholds) at the time of testing to the result record in the database.
- `Benchmarking` result status.
- `CompletedSpeedtestJob` to clearly define the end of the speedtest batch process.
- Don't complete a test until the last job has finished processing.
> [Feature] Added benchmarks to results table

- app/Jobs/Ookla/CompleteSpeedtestJob.php
- app/Jobs/SkipSpeedtestJob.php
This PR fixes writing the skipped tests are not marked as skipped
- Set the correct db schema for saving the IP  `'data->interface->externalIp' ` instead of `interface->externalIp' => $externalIp`
- CompletedSpeedtestJob ignored cancelled jobs which got them marks as completed instead of skipped
> [Bug] Fix Skipped Tests not marked as skipped

- app/Filament/Pages/Dashboard.php
- app/Helpers/Ookla.php
- config/speedtest.php
> [Feature] Added defined config servers to dropdown

- app/Actions/GetExternalIpAddress.php
- app/Actions/GetOoklaSpeedtestServers.php
- app/Filament/Pages/Dashboard.php
This PR fixes capturing curl errors when calling a URL especially when offline. 
- closes #1821 
- closes #1824 
- note to docs (https://docs.speedtest-tracker.dev/help/faqs#adguard-and-pi-hole-allow-domains) that `https://icanhazip.com/` needs to be added to your allow lists in AdGuard and Pi-hole.
- correctly capture errors when attempting to curl a URL for results.
> [Bug] Capture curl errors when offline

- app/Livewire/Topbar/RunSpeedtestAction.php
The button in the new toolbar is names "Dashboard" since its goes to the Public Dashboard it might be confusing with the normal Dashboard. This PR changes the name to Public Dashboard
- Change Dashboard to Public Dashboard
> [Feature] Change toolbar button to Public Dashboard

- app/Filament/Exports/ResultExporter.php
- app/Filament/Resources/ResultResource.php
This is a small QoL PR for the results table and export. 
- Add `Healthy` to the results export.
- Add `comments` to the results  pop up 
- Disable all the  Download / Upload Latencies  form the export by default.
> [Feature] Add Healhty to export and comments to column

- app/Filament/Widgets/RecentDownloadChartWidget.php
- app/Filament/Widgets/RecentDownloadLatencyChartWidget.php
- app/Filament/Widgets/RecentPingChartWidget.php
- app/Filament/Widgets/RecentUploadChartWidget.php
- app/Filament/Widgets/RecentUploadLatencyChartWidget.php
This is a small QoL improvement for the charts. 
- Add `grace` of 2 to some charts to not have the chart be at the bottom when there is a decrease in speed. 
- Change the Average to be a solid line instead of dotted, to fix the Legend looking strange
- closes https://github.com/alexjustesen/speedtest-tracker/issues/1864
Before: 
After
> [Feature] Change Average to solid line & Add grace 

- app/Policies/ResultPolicy.php
- app/Policies/UserPolicy.php
- closes #1889 
- no longer can update the authenticated user from the user resource, this should be done using your profile. 
- refactored policies to use `Illuminate\Auth\Access\Response` for permissions.
> [Chore] Update policies to use Illuminate\Auth\Access\Response

- app/Filament/Resources/ResultResource.php
- Closes https://github.com/alexjustesen/speedtest-tracker/issues/1935
- add the `queries` to the `TernaryFilter`.
> [Bug] Fix filtering on healthy in results table

- app/Helpers/Ookla.php
Sometimes, the Ookla CLI fails to execute the test due to an unknown error. Unfortunately, in such cases, the CLI does not return a complete JSON error response. Instead, it only provides: 
```
{
"error": "Cannot read: "
}
```
Our current logic expects a complete JSON response containing a `message` field. This PR introduces a placeholder error message for these cases, ensuring that failed tests are not left without an error message. 
As we cannot do anything about the reason of the failure this; 
- closes https://github.com/alexjustesen/speedtest-tracker/issues/1928
- closes https://github.com/alexjustesen/speedtest-tracker/issues/1862
- A placeholder message for failed cases without a `message` field.
> [Improvement] Add placeholder for failed test without message field

- app/Providers/AppServiceProvider.php
This PR adds custom Blade templates `@blank` and `@filled` to improve readability as it was rejected in the core: https://github.com/laravel/framework/pull/51561
- `@blank` and `@filled` Blade templates to improve readability.
Using `@blank()` in a view:
```php
// before
@if (blank())
i am blank
@endif
// after
@blank($var)
i am blank
@endblank
```
Using `@filled()` in a view:
```php
// before
@if (! blank($var))
i am not blank (filled)
@endif
// or
@if (filled($var))
i am not blank (filled)
@endif
// after
@filled($var)
i am not blank (filled)
@endfilled
```
> [Feature] Added custom "blank" and "filled" Blade directives

- app/Jobs/Ookla/RunSpeedtestJob.php
- `WithoutOverlapping` middleware on the `RunSpeedtestJob` to prevent multiple tests from running at the same time. This is not usually possible only if someone is using multiple queue workers.
> [Feature] Implement middleware to prevent overlapping execution of "RunSpeedtestJob"

- config/logging.php
closes #1957
- default log channel to `stderr` to expose logs to the container. This can be changed by setting the `LOG_CHANNEL` environment variable to other channels: https://laravel.com/docs/11.x/logging#available-channel-drivers
> [Chore] Add logging configuration file and set stderr as the default

- app/Jobs/Ookla/RunSpeedtestJob.php
- config/speedtest.php
This PR adds the option to specify the interface to use for the test. This way the user can specify is the tests need to run via a certain interface when using dockers `host` network or a specific docker network interface in case of multiple networks used for example a separate  IPv6 only network 
closes: https://github.com/alexjustesen/speedtest-tracker/issues/1301
closes: https://github.com/alexjustesen/speedtest-tracker/issues/615
Docs PR https://github.com/alexjustesen/speedtest-tracker-docs/pull/57
- Add the `interface` argument  to the command
- Add the environment variable to specify the interface to use.
> [Feature] Specify network interface to use

- app/Helpers/Ookla.php
This PR fixed that the placeholder messages is not shown more then onces, or with a valid Ookla error message. 
You can generate a non valid error message by running; `while true; do speedtest --accept-license --accept-gdpr --servers --format=json; sleep 1; done` after a couple of seconds you will get a rate limit message and the CLI won't run anymore. 
- closes https://github.com/alexjustesen/speedtest-tracker/issues/1962
Valid error json 
Non-valid error json.
> [Bug] Fix placeholder erorr messages

- app/Providers/AppServiceProvider.php
- config/api.php
- routes/api.php
This PR adds rate limiting to the API.
- rate limit API responses, can be configured using `API_RATE_LIMIT` environment variable. The default rate limit is 60 requests per minute.
> [Feature] Implement configurable API rate limiting

- app/Helpers/Bitrate.php
- app/Http/Controllers/Api/V1/ApiController.php
- app/Http/Controllers/Api/V1/Stats.php
- app/Http/Resources/V1/StatResource.php
- routes/api/v1/routes.php
This PR introduces a new `/api/v1/stats` endpoint that summaries `ping`, `download` and `upload` data. 
```bash
curl localhost/api/v1/stats
-H "Accept: application/json"
-H "Authorization: Bearer yourtokengoeshere"
```
By default this endpoint returns "all time" stats butyou can filter these stats by providing a `start_at` or `end_at` filter.
```bash
curl localhost/api/v1/stats?filter[start_at]>=2025-01-01
-H "Accept: application/json"
-H "Authorization: Bearer yourtokengoeshere"
curl localhost/api/v1/stats?filter[start_at]>=2024-01-01&filter[end_at]<=2024-12-31
-H "Accept: application/json"
-H "Authorization: Bearer yourtokengoeshere"
```
- `/api/v1/stats` endpoint
- round return from `bytesToBits` helper method
```json
{
"data": {
"ping": {
"avg": 7.44,
"min": 6.94,
"max": 9.41
}, …
```
> [Feature] Stats API endpoint

- app/Http/Controllers/Api/V1/ListResults.php
This PR fixes the filtering results on `api/v1/results` and point where the `created_at` date filter was not correctly aliased to allow for a range.
You can now filter this endpoint using `start_at` and `end_at`, both params are optional and expect a date or datetime.
- `start_at` and `end_at` aliases for `created_at` so results can be correctly filtered by date range.
- `updated_at` date filter, not needed IMO
> [Bug] Fixed dynamic filters for `start_at` and `end_at` in ListResults API

- app/Jobs/CheckForInternetConnectionJob.php
- app/Jobs/Ookla/BenchmarkSpeedtestJob.php
- app/Jobs/Ookla/CompleteSpeedtestJob.php
- app/Jobs/Ookla/RunSpeedtestJob.php
- app/Jobs/Ookla/SelectSpeedtestServerJob.php
- app/Jobs/Ookla/SkipSpeedtestJob.php
This PR attempts to fix the issues described in #1975, it looks like failed/overlapping jobs are preventing additional speedtest jobs from being run.
- refactored to use `SkipIfBatchCancelled` middleware on speedtest batch
- `WithoutOverlapping` middleware from `RunSpeedtestJob`
> [Bug] Removed WithoutOverlapping middleware and refactored to use SkipIfBatchCancelled

- app/Filament/Resources/ResultResource.php
- app/Filament/Resources/ResultResource/Pages/ListResults.php
- app/Filament/Widgets/RecentDownloadChartWidget.php
- app/Filament/Widgets/RecentDownloadLatencyChartWidget.php
- app/Filament/Widgets/RecentJitterChartWidget.php
- app/Filament/Widgets/RecentPingChartWidget.php
- app/Filament/Widgets/RecentUploadChartWidget.php
- app/Filament/Widgets/RecentUploadLatencyChartWidget.php
- app/Filament/Widgets/StatsOverviewWidget.php
- app/Providers/Filament/AdminPanelProvider.php
- config/speedtest.php
Page / table / chart / notification refresh polling was introduced early on. This config has been removed and replaced with sensible defaults in preparation for a refactor of the dashboard and results table.
- replaced polling config with sensible defaults
- defer loading of `Results` table
> [Chore] Removed polling config

- app/Filament/VersionProviders/SpeedtestTrackerVersionProvider.php
#2053 Introduced a bug that the systemchecker is still used in the `SpeedtestTrackerVersionProvider`. I missed that one.
closes https://github.com/alexjustesen/speedtest-tracker/issues/2077 
closes https://github.com/alexjustesen/speedtest-tracker/issues/2078
- Change systemchecker to the config.
> [Bug] Fix systemchecker in SpeedtestTrackerVersionProvider

- lang/zh_TW/auth.php
- lang/zh_TW/pagination.php
- lang/zh_TW/passwords.php
- lang/zh_TW/validation.php
Add a basic zh_TW Traditional Chinese locale
- A basic zh_TW Traditional Chinese locale
> Add a basic zh_TW Traditional Chinese locale

- config/database.php
This PR published the `database.php` config file and added `search_path` as an environment variable option. Based on https://stackoverflow.com/questions/45242702/how-to-set-default-postgresql-schema-for-laravel#45242853
- closes #2156 
https://docs.speedtest-tracker.dev/getting-started/database-drivers#postgres
- `DB_SEARCH_PATH` as environment variable to set Postgres schema
- published `config/database.php`
> [Bug] Published database config and added DB_SEARCH_PATH as env variable

- app/Http/Middleware/AllowedIpAddressesMiddleware.php
- bootstrap/app.php
- config/speedtest.php
This PR adds allowed IPs middleware to the `api` and `web` groups and will prevent any requests if any IP addresses are specified. `ALLOWED_IPS` can be set to an IP address (`127.0.0.1`) or a list of IP addresses (`127.0.0.1,127.0.0.2`).
- closes #2159 
https://docs.speedtest-tracker.dev/getting-started/environment-variables#application
- `ALLOWED_IPS` to allow only certain IP addresses from accessing the application.
> Added allowed IPs

- app/Actions/Ookla/StartSpeedtest.php
- app/Enums/ResultStatus.php
- app/Events/SpeedtestWaiting.php
- app/Filament/Pages/ApiTokens.php
- app/Http/Controllers/Api/V1/ApiController.php
- app/Http/Controllers/Api/V1/RunSpeedtest.php
- app/Jobs/Ookla/ProcessSpeedtestBatch.php
- app/Jobs/Ookla/StartSpeedtestJob.php
- database/migrations/2025_05_19_160458_reset_existing_api_token_abilities.php
- routes/api/v1/routes.php
This PR introduces a new `POST` request endpoint `/api/v1/speedtests/run` to run a speedtest via the API. The API will respond with the result ID and a new status of "waiting".
This PR expands on the work started in #2201.
- closes #1047 
https://docs.speedtest-tracker.dev/api/v1#run-speedtest
- API abilities for `results:read` and `speedtests:run`, on deployment/update all existing token will be scoped to the `results:read` ability only. To use `speedtests:run` a new API token needs to be created.
- "waiting" result status for when a speedtest was created in the database but has not been picked up by a queue worker.
- removed `ID` column from API tokens list and added `created_at` date.
> Run Speedtests from the API

- lang/es_ES/auth.php
- lang/es_ES/pagination.php
- lang/es_ES/passwords.php
- lang/es_ES/validation.php
Added the Spanish translation based on the existing languages (mainly Italian)
- lang/es_ES/auth.php
- lang/es_ES/pagination.php
- lang/es_ES/passwords.php
- lang/es_ES/validation.php
> Add Spanish  (es_ES) localization

- lang/nl_NL/auth.php
- lang/nl_NL/pagination.php
- lang/nl_NL/passwords.php
- lang/nl_NL/validation.php
This update introduces Dutch language support to Speedtest Tracker, enhancing its multilingual functionality. Enabling Dutch-speaking users to interact with Speedtest Tracker in their native language.
- Translated the following content in `lang/nl_NL`:
- `auth.php`
- `pagination.php`
- `passwords.php`
- `validation.php`
> [!NOTE]
> The source of truth for the language is based on `de_DE`, as the English translations (`en`) are not fully complete.
> feat: Add Dutch Translation (I18N) Support

- .github/workflows/inactivity-actions.yml
📃 Description
This pull request introduces a unified GitHub Actions workflow to handle repository hygiene tasks, specifically locking inactive issues/PRs and closing stale issues. It replaces previously separate workflows with a single, maintainable issue_pr_maintenance.yml. This prevents people from commenting on old issues and send notifications to others.
> action-inactivity-lock is not able to exclude PRs, set it to 120 to give it enough time before locking
📖 Documentation
No documentation changes required for this PR.
🪵 Changelog
➕ Added
- New issue_pr_maintenance.yml GitHub Actions workflow
- Locking job using klaasnicolaas/action-inactivity-lock@v1.1.3
- Closing stale question issues using actions/stale@v9
📷 Screenshots
Not applicable – this PR does not include UI changes.
> [Chore] Lock inactive issues and PRs

- app/Actions/Influxdb/v2/BuildPointData.php
This PR fixes the Influxdb BuildPointData causing the export to fail, after https://github.com/alexjustesen/speedtest-tracker/pull/2256
Fixes https://github.com/alexjustesen/speedtest-tracker/issues/2270
- Add the missing `Arr::get` to `downloaded_bytes` and `uploaded_bytes`
- Change type to `float` as well
> [Bug] Fix missing Get and type in BuildPointData

- docker/8.3/Dockerfile
Ensure the Dockerfile fetches the correct ARM binary for Speedtest CLI, so I’m not left wondering why tests fail during development. 🙄
> [Chore] ARM Speedtest CLI installation method in Dockerfile

- .env.ci
- .github/workflows/ci.yml
- phpunit.xml
- closes #1942 
Add a link to the PR for [documentation](https://github.com/alexjustesen/speedtest-tracker-docs) changes.
- separate ci pipeline tests for sqlite, mysql and pgsql databases
> Added multi-database architecture CI pipeline

- app/Http/Middleware/AcceptJsonMiddleware.php
- app/OpenApi/Annotations/V1/OoklaAnnotations.php
- app/OpenApi/Annotations/V1/ResultsAnnotations.php
- app/OpenApi/Annotations/V1/SpeedtestAnnotations.php
- app/OpenApi/Annotations/V1/StatsAnnotations.php
- app/OpenApi/OpenApiDefinition.php
- app/OpenApi/Schemas/NotAcceptableErrorSchema.php
- bootstrap/app.php
- openapi.json
- routes/api.php
- tests/Unit/AcceptJsonMiddlewareTest.php
This PR adds `Accept: application/json` as a required header for API calls.
> API requires accept json header
