alexjustesen/speedtest-tracker

- app/Jobs/ExecSpeedtest.php
- config.example.yml
Missing arg for GDPR ack: check issue #19
> GDPR ack option

- app/Filament/Resources/ResultResource.php
- app/Tables/Columns/ServerColumn.php
- resources/views/tables/columns/server-column.blade.php
- server info to results table
> Show server in results table

- app/helpers.php
> When converting bits its to the power of 1000 not 1024

- .github/dependabot.yml
With the current configuration it will monitor docker base images, github actions, and composer dependencies for updates.
If an update is found it will automatically create the nessisary PR for review.
> Setup Dependabot for automatic depdendency updates

- config/filament.php
- database/migrations/2022_10_24_152031_create_notifications_table.php
- database notifications to Filament
> Added database notifications to filament

- app/Filament/Pages/Settings/GeneralPage.php
- app/Filament/Pages/Settings/InfluxDb.php
- app/Filament/Pages/Settings/InfluxDbPage.php
- app/Filament/Pages/Settings/NotificationPage.php
- app/Filament/Pages/Settings/ThresholdsPage.php
- app/Forms/Components/TestDatabaseNotification.php
- app/Jobs/SendDataToInfluxDbV2.php
- app/Observers/ResultObserver.php
- app/Settings/NotificationSettings.php
- app/Settings/ThresholdSettings.php
- app/helpers.php
- config/filament.php
- database/settings/2022_10_24_153150_create_database_notifications_settings.php
- database/settings/2022_10_24_153411_create_thresholds_settings.php
- resources/views/filament/forms/notifications-helptext.blade.php
- resources/views/filament/forms/thresholds-helptext.blade.php
- resources/views/forms/components/test-database-notification.blade.php
- database notification settings
- threshold settings and threshold database notifications
_Database Notification Settings_
_Absolute Thresholds Settings_
_Database Notification Example_
> Performance thresholds

- app/Policies/FailedJobPolicy.php
- app/Providers/AuthServiceProvider.php
- composer.json
- composer.lock
To use the failed job viewer update `APP_DEBUG` to `true` in your `.env` file
- failed job viewer to assist with debugging
> Failed jobs viewer

- app/Filament/Pages/Settings/GeneralPage.php
Noticed a typo, nothing major!
> chore: fix typo

- docker/8.1/cron/scheduler
- docker/deploy/cron/scheduler
> Disabled crontab mail

- .github/workflows/publish-image.yml
> Added linux/arm/v7 to build platforms

- app/Observers/ResultObserver.php
Ref: alexjustesen/speedtest-tracker#90
> fix sending data to influxdb

- app/Models/Result.php
closes #144 
Also... not a clue why casting `data` as an `array` isn't working so I'm doing it the manual way for now.
> Influxdb data failure

- app/Models/Result.php
> made additional metrics nullable in case they're not available

- app/Providers/FilamentServiceProvider.php
- config/filament.php
- enabled collapsible sidebar nav, closes #174 
- updated sidebar nav icons
> Collapsible sidebar nav

- app/Providers/FilamentServiceProvider.php
> added back filament logs

- .github/workflows/publish-image.yml
- build and publish image to Docker Hub
> build and publish image to Docker Hub

- .github/workflows/cd-docker-hub.yml
- app/Providers/FilamentServiceProvider.php
- missing platform builds
- duplicate registry login
> Remove cd duplicate login

- app/Filament/Widgets/RecentJitterChart.php
- app/Filament/Widgets/RecentPingChart.php
- app/Filament/Widgets/RecentSpeedChart.php
> dynamic y axis on charts

- app/Filament/Widgets/StatsOverview.php
- added date to latest result stats, closes #182
> added date to latest result stats

- app/Filament/Resources/ResultResource.php
- added jitter columns to result resource, closes #48
> added jitter columns to result resource

- app/Filament/Pages/Dashboard.php
- resources/views/filament/pages/dashboard.blade.php
- last run date does not poll for updates, closes #251
> Last run date polling

- app/Filament/Pages/Settings/NotificationPage.php
- require recipient email address
closes #269
> require recipient email address

- database/migrations/2023_01_05_210719_create_cache_table.php
- database cache driver support
This might resolve the issue in #127
> added database cache driver support

- app/Filament/Resources/UserResource.php
- app/Filament/Resources/UserResource/Pages/CreateUser.php
- app/Filament/Resources/UserResource/Pages/EditUser.php
- app/Filament/Resources/UserResource/Pages/ListUsers.php
Added small CRUD to manage users
> User management

- app/Filament/Pages/Settings/GeneralPage.php
- select a manually entered server ID if the search returns no results, closes #314
> select a manually entered server ID

- .github/workflows/cd-docker-hub.yml
Using the secrets.DOCKER_USERNAME and GitHub repository name to form docker image for docker hub.
It should make this workflow more reusable.
> Unhardcoding cd-docker-hub.yml

- .github/workflows/cd-docker-hub.yml
> Added versioned tag alongside latest on docker-hub deployment

- app/Filament/Pages/Settings/GeneralPage.php
From a conversation in #336 removed the message that auth will be disabled as this is no longer planned.
> removed auth message

- app/Exports/ResultsSelectedBulkExport.php
- app/Filament/Resources/ResultResource.php
- export selected result records to csv, closes #353
> Export selected result records

- app/Filament/Resources/ResultResource.php
- app/Models/Result.php
- database/migrations/2023_02_12_131620_add_comments_to_results_table.php
- `comments` to the `Results` model, closes #379
> Result comments

- docker-compose.yml
- docker/8.1/Dockerfile
- docker/8.1/cron/scheduler
- docker/8.1/php.ini
- docker/8.2/Dockerfile
- docker/8.2/php.ini
- docker/8.2/start-container
- docker/8.2/supervisord.conf
- `php8.2` config for later use
- include `mysql` by default for local development
- removed dependencies in the image what aren't being used
- move `cron` task to inline instead of a separate file
- `mailhog` is no longer maintained, switched to `mailpit` for smtp testing
> Local development env updates

- app/Filament/Pages/Settings/InfluxDbPage.php
- app/Jobs/SendDataToInfluxDbV2.php
- app/Settings/InfluxDbSettings.php
- database/settings/2023_03_06_002044_add_verify_ssl_to_influx_db_settings.php
- option to enable or disable `verifySSL` config, #424 
_InfluxDB Settings_
> InfluxDB verify ssl

- app/helpers.php
- force removal of the comma to number formatting, closes #479
> [Bugfix] toBits number format

- app/Jobs/SendDataToInfluxDbV2.php
- app/Models/Result.php
null check for `packetLoss` and passing the `verifySSL` value to the client
> #443 passing verifySSL to the client

- .gitignore
- composer.json
- tests/Feature/ExampleTest.php
- tests/Unit/ExampleTest.php
This pull request contains changes for upgrading to [PHPUnit 10](https://phpunit.de/announcements/phpunit-10.html) automated by the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10).
- Checkout the `shift-90290` branch
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Run your tests suite: `vendor/bin/phpunit`
If there were changes you felt could have been automated, please reply to the follow-up email with your feedback or on [Twitter](https://twitter.com/laravelshift).
> PHPUnit 10 Shift

- composer.json
- composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.10.0` branch.
- Checkout the `shift-ci-v10.10.0` branch
> Laravel 10.10.0 Shift

- composer.json
- composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.13.2` branch.
- Checkout the `shift-ci-v10.13.2` branch
> Laravel 10.13.2 Shift

- Dockerfile
- config/filament.php
- config/speedtest.php
- docker-compose.yml
This PR increases the polling intervals so that less resources are used when the dashboard or results page are left open.
- default polling intervals
> [Bugfix] Longer polling times

- routes/web.php
> [Bugfix] Server error on password change

- app/Jobs/SendDataToInfluxDbV2.php
- app/Models/Result.php
- composer.json
- composer.lock
This PR fixes `packet_loss` type, closes #725 
- upgraded influxdb client to `^3.x`
- `packet_loss` type error
> [Bugfix] Influxdb packet loss type

- app/Providers/Filament/AdminPanelProvider.php
> added back collapsible sidebar

- app/Filament/Pages/Settings/GeneralPage.php
- app/Filament/Pages/Settings/InfluxDbPage.php
- app/Filament/Pages/Settings/NotificationPage.php
- app/Filament/Pages/Settings/ThresholdsPage.php
This PR fixes a brain fart.
- mount the parent method instead of calling each function again
> [Bugfix] Mount parent method on settings pages

- config/speedtest.php
> Release v0.12.0

- app/Filament/Pages/Settings/GeneralPage.php
> [Chore] Added ID to manually entered server

- app/Filament/Pages/Settings/GeneralPage.php
This PR brings back the preloaded list and bumps the number of results to 20 which is the max the CLI will return.
- preloaded server list back
- faq item to the [docs](https://docs.speedtest-tracker.dev/faqs#q-why-do-only-some-servers-have-the-server-name-in-the-list) to explain why some servers don't display names
- bumped to 20 results
> [Feature] Preload server list and bump to 20 results

- app/Providers/Filament/AdminPanelProvider.php
This PR enables SPA mode which makes use of Livewire's `:navigate` function to make the pages render faster.
- enabled spa mode in Filament
> [Feature] Enabled SPA mode

- app/Filament/Pages/Dashboard.php
- app/Filament/Resources/ResultResource.php
- app/Filament/Resources/UserResource.php
- app/Providers/Filament/AdminPanelProvider.php
This PR adds a nav item link to the front end home page in the admin panel.
- home nav item in the admin panel
- "dashboard" page nav icon
> [Feature] Added home nav item

- app/Console/Commands/UpdateGeneralSettings.php
- app/Helpers/TimeZoneHelper.php
This PR introduces a CLI command to update the general settings which will hopefully help solve the `500 error` on that page. Might help fix issues like in #943.
1. Open the terminal of the container.
2. Run `php artisan app:update-general-settings`.
3. Follow the prompts.
- cli to update general settings
> [Feature] CLI to update general settings

- app/Http/Middleware/FrameAllowOptions.php
Attempting to fix the CORS issue when embedding the dashboard.
- use set method to change `X-Frame-Options` header
> [Bug] Set x-frame-options header

- app/Http/Middleware/VerifyCsrfToken.php
Tied to #1024, and forgot it in #1025.
- livewire csrf exception
> [Bug] Removed Livewire csrf exception

- composer.json
- platform php version to `composer.json`
> [Chore] specified platform php version

- app/Models/Result.php
- refactored `getJitterData()` method on `Result` model
> [Chore] Refactored get jitter data method

- app/Actions/GetOoklaSpeedtestServers.php
- app/Filament/Pages/Settings/GeneralPage.php
This PR refactors and extracts to an action getting Ookla's speedtest server list.
- closes #1101
- refactored getting Ookla's speedtest server list
> [Chore] Refactored getting Ookla speedtest servers

- app/Filament/Pages/Settings/NotificationPage.php
- app/Settings/NotificationSettings.php
- database/settings/2024_02_07_173217_add_telegram_disable_notification_to_notification_settings.php
This PR adds a Telegram channel option to send the notification to recipients silently.
- closes #868
- setting to silently send Telegram notifications to the recipients
> [Feature] Silently send notifications for Telegram

- app/Filament/VersionProviders/SpeedtestTrackerVersionProvider.php
- app/Providers/Filament/AdminPanelProvider.php
- missing version provider namespace
> [Bug] Fixed missing version provider namespace

- database/migrations/2024_02_18_100000_results_bad_json_table.php
Bad logic, I need a drink or something.
> Hotfix v0.16.2

- app/Filament/Resources/ResultResource.php
- closes #1161 
- don't select null external IP addresses
> [Bug] Don't select null external IP addresses

- app/Filament/Resources/ResultResource.php
- app/Filament/Widgets/StatsOverviewWidget.php
- app/Helpers/Number.php
This PR updates the bit number helps and separates them into `bitsToHuman` and `toBitRate` methods.
- `bitsToHuman` and `toBitRate` number helpers
> [Chore] Bit number helpers

- app/Helpers/Number.php
This PR introduces a new number helper `bitsToMagnitude` to convert bits to a specific magnitude which is foundational to #1176.
- `bitsToMagnitude` number help
> [Feature] Added bit to magnitude helper

- _ide_helper.php
- composer.json
- composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.45.1` branch.
- Checkout the `shift-ci-v10.45.1` branch
> Laravel 10.45.1 Shift

- app/Filament/Resources/ResultResource.php
- sortable query for json data, closes #1248
> [Bug] Fixed sortable query for json data

- app/Listeners/SpeedtestCompletedListener.php
- app/Listeners/Threshold/AbsoluteListener.php
Closes #1235 
N/A
N/A
Fixed how discord notifications in `AbsoluteListener.php` handles bits vs bytes. 
N/A
N/A
> Refactored Discord Notifications to fix threshold notifications

- app/Filament/Resources/ResultResource.php
- view result created at timezone, closes #1261
> [Bug] Fixed view created at timezone

- app/Listeners/SpeedtestCompletedListener.php
- app/Listeners/Threshold/AbsoluteListener.php
- app/Listeners/Webhook/SendSpeedtestCompletedNotification.php
- app/Listeners/Webhook/SendSpeedtestThresholdNotification.php
- app/Providers/EventServiceProvider.php
- refactored webhook notification listeners
> [Chore] Refactored webhook notifications to their own listeners

- database/factories/ResultFactory.php
- result factory with fake data
> [Bug] Result factory with fake data

- app/Listeners/SpeedtestCompletedListener.php
- app/Listeners/Telegram/SendSpeedtestCompletedNotification.php
- app/Listeners/Telegram/SendSpeedtestThresholdNotification.php
- app/Listeners/Threshold/AbsoluteListener.php
- app/Notifications/Telegram/SpeedtestNotification.php
- app/Providers/EventServiceProvider.php
- resources/views/emails/speedtest-threshold.blade.php
- resources/views/telegram/speedtest-completed.blade.php
- resources/views/telegram/speedtest-threshold.blade.php
- resources/views/telegram/threshold/absolute.blade.php
- refactored Telegram notification listeners
> [Chore] Refactored Telegram notifications to their own listeners

- app/Jobs/InfluxDBv2/WriteCompletedSpeedtest.php
- app/Listeners/Data/InfluxDb2Listener.php
- refactored InfluxDBv2 data listener
> [Chore] Refactored InfluxDBv2 data listener

- app/Filament/Pages/Dashboard.php
- use server list when running manual speedtests
> [Bug] Use server list when running manual speedtests

- app/Helpers/Number.php
- app/helpers.php
- divide by zero, closes #1326
> [Bug] Divide by zero

- app/Enums/ResultStatus.php
- app/Enums/UserRole.php
- app/Filament/Resources/ResultResource.php
- app/Filament/Resources/UserResource.php
- app/Models/User.php
Nothing fancy, just more consistency across enums, labels and colors.
- `UserRole` enum
> [Chore] Badges labels and color updates

- app/Console/Commands/ResetUserPassword.php
> [Bug] removed extra $ in password reset error message

- app/Filament/Resources/UserResource.php
- app/Providers/Filament/AdminPanelProvider.php
This PR adds a "Profile" link to the navbar so the authenticated user can update their information.
- Filament's user profile
> [Feature] added filament user profile

- config/app.php
Resolves the issue pointed out here https://github.com/linuxserver/docker-speedtest-tracker/pull/19#issuecomment-2154783146
> [Bug] Default display timezone to utc

- app/Listeners/Telegram/SendSpeedtestCompletedNotification.php
- resources/views/telegram/speedtest-completed.blade.php
> [Chore Round package loss in telegram notification

- app/Mail/SpeedtestCompletedMail.php
- resources/views/emails/speedtest-completed.blade.php
> [Bug] Fixed result reference in speedtest completed mail

- app/Filament/Pages/Dashboard.php
This PR makes the chart order consistent between the public dashboard and admin dashboard.
- swapped download and upload jitter charts
> swapped download and upload charts

- app/Actions/MigrateBadJsonResults.php
- app/Actions/Notifications/SendMailTestNotification.php
- app/Filament/Resources/ResultResource.php
- app/Listeners/Data/InfluxDb2Listener.php
- app/Listeners/Database/SendSpeedtestCompletedNotification.php
- app/Listeners/Database/SendSpeedtestThresholdNotification.php
- app/Listeners/Discord/SendSpeedtestCompletedNotification.php
- app/Listeners/Discord/SendSpeedtestThresholdNotification.php
- app/Listeners/Gotify/SendSpeedtestCompletedNotification.php
- app/Listeners/Gotify/SendSpeedtestThresholdNotification.php
- app/Listeners/HealthCheck/SendSpeedtestCompletedNotification.php
- app/Listeners/HealthCheck/SendSpeedtestThresholdNotification.php
- app/Listeners/Mail/SendSpeedtestCompletedNotification.php
- app/Listeners/Mail/SendSpeedtestThresholdNotification.php
- app/Listeners/Ntfy/SendSpeedtestCompletedNotification.php
- app/Listeners/Ntfy/SendSpeedtestThresholdNotification.php
- app/Listeners/Pushover/SendSpeedtestCompletedNotification.php
- app/Listeners/Pushover/SendSpeedtestThresholdNotification.php
- app/Listeners/Slack/SendSpeedtestCompletedNotification.php
- app/Listeners/Slack/SendSpeedtestThresholdNotification.php
- app/Listeners/Telegram/SendSpeedtestCompletedNotification.php
- app/Listeners/Telegram/SendSpeedtestThresholdNotification.php
- app/Listeners/Webhook/SendSpeedtestCompletedNotification.php
- app/Listeners/Webhook/SendSpeedtestThresholdNotification.php
- app/Notifications/Telegram/TestNotification.php
- app/Providers/Filament/AdminPanelProvider.php
- database/migrations/2024_02_18_100000_results_bad_json_table.php
- database/migrations/2024_02_19_134706_create_imports_table.php
- database/migrations/2024_02_19_134707_create_exports_table.php
- database/migrations/2024_02_19_134708_create_failed_import_rows_table.php
This PR fixes all the problems with the new lint version. Just the suggested changes by lint :)
> Fixes for new lint requirements 

- app/Filament/Resources/UserResource.php
- app/Filament/Resources/UserResource/Pages/EditUser.php
This PR expands on the improvements started in #1732 
- refactored user resource
> [Chore] Refactor user resource

- app/Filament/Exports/ResultExporter.php
> [Feature] Added result url to export

- app/Listeners/Discord/SendSpeedtestCompletedNotification.php
- app/Listeners/Discord/SendSpeedtestThresholdNotification.php
- app/Listeners/Gotify/SendSpeedtestCompletedNotification.php
- app/Listeners/Gotify/SendSpeedtestThresholdNotification.php
- app/Listeners/Ntfy/SendSpeedtestCompletedNotification.php
- app/Listeners/Ntfy/SendSpeedtestThresholdNotification.php
- app/Listeners/Pushover/SendSpeedtestCompletedNotification.php
- app/Listeners/Pushover/SendSpeedtestThresholdNotification.php
- app/Listeners/Slack/SendSpeedtestCompletedNotification.php
- app/Listeners/Slack/SendSpeedtestThresholdNotification.php
- app/Listeners/Telegram/SendSpeedtestCompletedNotification.php
- app/Listeners/Telegram/SendSpeedtestThresholdNotification.php
- app/Mail/SpeedtestCompletedMail.php
- app/Mail/SpeedtestThresholdMail.php
> [Bug] Fixed service enum label

- app/Filament/Widgets/RecentPingChartWidget.php
- closes #1825 
- high ping values not showing in charts
> [Bug] Fixed high ping values not showing in charts

- app/Filament/Widgets/RecentDownloadChartWidget.php
- app/Filament/Widgets/RecentDownloadLatencyChartWidget.php
- app/Filament/Widgets/RecentJitterChartWidget.php
- app/Filament/Widgets/RecentUploadChartWidget.php
- app/Filament/Widgets/RecentUploadLatencyChartWidget.php
Extends https://github.com/alexjustesen/speedtest-tracker/pull/1827 for the ohter charts.
> [Bug] High values not showing in charts

- app/Filament/Pages/Dashboard.php
- app/Livewire/Topbar/RunSpeedtestAction.php
- app/Providers/FilamentServiceProvider.php
- bootstrap/providers.php
- public/css/app/panel.css
- resources/css/panel.css
- resources/views/livewire/topbar/run-speedtest-action.blade.php
The PR adds dashboard buttons to the toolbar so they're available on every page in the admin panel.
- "Public Dashboard" and "Run Speedtest" buttons to the toolbar
> [Feature] Added dashboard buttons to the toolbar

- app/Actions/Influxdb/v2/BuildPointData.php
- app/Helpers/Number.php
This PR casts Influxdb point values to specific types regardless of the type stored.
> [Bug] Cast Influxdb point values

- resources/views/discord/speedtest-completed.blade.php
- resources/views/discord/speedtest-threshold.blade.php
- resources/views/gotify/speedtest-completed.blade.php
- resources/views/gotify/speedtest-threshold.blade.php
- resources/views/ntfy/speedtest-completed.blade.php
- resources/views/ntfy/speedtest-threshold.blade.php
- resources/views/pushover/speedtest-completed.blade.php
- resources/views/pushover/speedtest-threshold.blade.php
- resources/views/slack/speedtest-completed.blade.php
- resources/views/slack/speedtest-threshold.blade.php
- resources/views/telegram/speedtest-completed.blade.php
- resources/views/telegram/speedtest-threshold.blade.php
This PR adds the App name to the notifications to close https://github.com/alexjustesen/speedtest-tracker/issues/1879
- App name to the notifications
> [Feature] Add App Name to notifications

- app/Jobs/Influxdb/v2/TestConnectionJob.php
closes #1888
- create a fake data point without using the model factory
> [Bug] Don't use factory to test influxdb connection

- config/speedtest.php
- package-lock.json
> Release v1.0.0

- app/Jobs/Ookla/SelectSpeedtestServerJob.php
> [Bug] Fix logic to check for existing server ID in SelectSpeedtestServerJob

- composer.json
- composer.lock
This pull request includes updates for the recent patch version release of Laravel as well as bumps your package dependencies. You may review the full list of changes in the [Laravel Release Notes](https://github.com/laravel/framework/releases/tag/v11.36.1).
- Checkout the `shift-ci-v11.36.1` branch
> Laravel 11.36.1 Shift

- app/Filament/Pages/ApiTokens.php
- composer.json
- composer.lock
- resources/views/filament/pages/api-tokens.blade.php
This PR implements generating API tokens for the upcoming API endpoints.
- generate and manage api tokens
> [Feature] Add API Tokens management page

- config/speedtest.php
- routes/console.php
> [Bug] Cast `prune_results_older_than` as integer

- app/Filament/Resources/ResultResource.php
> [Bug] Fixed server name filter

- routes/console.php
> [Bug] Fixed models are not being pruned when enabled

- composer.json
- composer.lock
This pull request includes updates for the recent patch version release of Laravel as well as bumps your package dependencies. You may review the full list of changes in the [Laravel Release Notes](https://github.com/laravel/framework/releases/tag/v11.43.2).
- Checkout the `shift-ci-v11.43.2` branch
> Laravel 11.43.2 Shift

- config/speedtest.php
> Release v1.2.5

- config/speedtest.php
> Release v1.3.0

- .github/dependabot.yml
This PR adds Composer and NPM to dependabot to close https://github.com/alexjustesen/speedtest-tracker/issues/2123 
N/A
- Add Composer and NPM to dependabot
- Remove the emoji from the label
> [Chore] Add Composer and NPM to dependabot

- app/Filament/Exports/ResultExporter.php
- app/Filament/Resources/ResultResource.php
This PR refactors the Results exporter to export all the colunms all the time. We automatically split the data colunm during the export, this way all the data is there. 
N/A
- Add a Confirm pop up when exporting all results.
- two
- Export all colunms by default
If this PR has any UI/UX changes it's strongly suggested you add screenshots here.
> [Chore] Refactor Results Exporter

- .github/workflows/stale_issues.yml
Reverts alexjustesen/speedtest-tracker#2258
> Revert "[Chore] Lock inactive issues and PRs"

- app/Actions/Notifications/SendWebhookTestNotification.php
Fixes https://github.com/alexjustesen/speedtest-tracker/issues/2275
- Add missing `Str`
> [Bug] Fix failing webhook test generator

- resources/views/getting-started.blade.php
> Fix getting started page text colors on light theme

- app/Actions/Influxdb/v2/BuildPointData.php
This PR fixes the influxdb Data export, fixed https://github.com/alexjustesen/speedtest-tracker/issues/2337
- Changes `result->data, 'download_bytes'` to `$result->download_bytes,`
> [Bug] Fix Influxdb export 
